### ISSUE TITLE
Add option for dirac to customize or provide default for runtime-tag

### ISSUE THREAD

**Issue by jupl** [jupl/boot-cljs-devtools#2]

**Comment by arichiardi** [comment]
In general it would be good to be able to pass a [config](https://github.com/binaryage/dirac/blob/master/src/agent/dirac/agent/config.clj#L4) to `dirac` from the task, for instance I would like to spin up my repl and connect to it, would you be open to a patch?

**Comment by arichiardi** [comment]
See #3

**Comment by jupl** [comment]
I had this originally because of the warning in Dirac. It got removed later but if the PR works then I'll probably merge anyway.

**Comment by arichiardi** [comment]
Solved by #3
