### ISSUE TITLE
In presence of a watch task runtime is installed multiple times

### ISSUE THREAD

**Issue by arichiardi** [jupl/boot-cljs-devtools#8]
My pipeline is surrounded by a `watch` and `reload` and I see many times the string:

```
Adding :require [devtools.core dirac.runtime] and :init-fns [devtools.core/install! dirac.runtime/install!] to main.cljs.edn...
```

Is there a way to detect if dirac/devtools is installed already and skip it? I will ask on Slack, just opened this for reminding it to myself :smile:

**Comment by martinklepsch** [comment]
@arichiardi IIRC you should also see these messages for `reload` and other tasks, it's a bit of an "unsolved problem" because users can theoretically modify the .cljs.edn files which would then override the injections done by tasks. Hope this makes sense.

**Comment by arichiardi** [comment]
Right, make sense then, closing this!
